# Generated by Django 4.2.5 on 2023-10-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0002_alter_stock_category_alter_stock_item_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Categoria')),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(choices=[('it-periferics', 'IT Periferics'), ('hardware', 'Hardware'), ('software', 'Software')], max_length=50, null=True),
        ),
    ]
