# Generated by Django 4.2.5 on 2023-10-21 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0006_remove_stock_export_to_csv_remove_stock_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado'),
        ),
    ]
